#!/bin/bash

if git status --porcelain -- doc/hyperdrive.org | grep "^M" > /dev/null
then
    # hyperdrive.org has staged changes
    make doc
    if git status --porcelain -- doc/hyperdrive.texi | grep "^ M" > /dev/null
    then
        # After export, hyperdrive.texi has unstaged changes
        echo "hyperdrive.texi may need to be added"
        exit 1
    else
        exit 0
    fi
else
    exit 0
fi
